device: 'cuda'
gamma: 0.2
nb_epochs: 100
batch_size: 64

save_model_path: '/models_checkpoints/factorvae/without_discr'
dataset_path: '/dsprites-dataset/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz'

factorvae: 
  input_dim: 64
  h_dim1: 32
  h_dim2: 64
  kernel_size: 4
  stride: 2
  fc_dim: 128
  output_dim: 10
  batch_size: 64
  vae_lr: 0.0001 # initially 0.0001
  vae_beta1: 0.9
  vae_beta2: 0.999

discr: 
  input_dim: 10 # same output_dim of the factorVAE
  hidden_dim: 1000
  output_dim: 2
  discr_lr: 0.0001
  discr_beta1: 0.5
  discr_beta2: 0.9

